name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.CI_CD }}

      - name: Build
        run: eas build --platform android --profile preview --non-interactive --no-wait